name: Update Design CSS

on:
  push:
    branches: 4.4
    paths:
      - 'docs/css/design.css'

jobs:
  update-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update local design.css
        run: |
          # Replace with your desired logic to update the local design.css file
          # For example, you can use wget or curl to download the latest design.css
          # from the repository.
          wget https://raw.githubusercontent.com/pmcf-percona/docs-home/main/docs/css/design.css -O design.css
          # Or use curl:
          # curl -o design.css https://raw.githubusercontent.com/pmcf-percona/docs-home/main/docs/css/design.css

      #Configure git
      - name: Configure git
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: |
          git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"
          git config user.name "GitHub Action"
          git config user.email "github-action@users.noreply.github.com"
          git config user.password "${ROBOT_TOKEN}"
          echo "GIT_USER=percona-platform-robot:${ROBOT_TOKEN}" >> $GITHUB_ENV
      
      - name: Commit changes
        run: |
          git add design.css
          git commit -m "Update design.css"
          git push
